engines:
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
  duplication:
    enabled: true
    config:
        languages:
        - php
        - javascript
  eslint:
    enabled: true
  csslint:
    enabled: true

ratings:
  paths:
  - app/**
  - "**.php"
  - "**.js"

exclude_paths:
  - app/Admin/public/**/*
  - app/Front/public/**/*
  - app/Data/database/**/*
  - database/**/*
  - public/vendor/**/*
  - public/assets/**/*
  - public/js/**/*
  - tests/**/*
